// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzYDJLcQjlS-bVVCaz4z7hzs9mkVVayD0',
    appId: '1:223539143896:web:29976875b9712caa85a3ad',
    messagingSenderId: '223539143896',
    projectId: 'kaihe-54d62',
    authDomain: 'kaihe-54d62.firebaseapp.com',
    storageBucket: 'kaihe-54d62.appspot.com',
    measurementId: 'G-ZG2VGM8K7L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyXFAACQrC5ZY2epnK5ftvW70R8isddSc',
    appId: '1:223539143896:android:5498fcedcd32780a85a3ad',
    messagingSenderId: '223539143896',
    projectId: 'kaihe-54d62',
    storageBucket: 'kaihe-54d62.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIexG-xQhFs2o-mKivwTPy3mMLdZlvwRg',
    appId: '1:223539143896:ios:c43d81737538fba885a3ad',
    messagingSenderId: '223539143896',
    projectId: 'kaihe-54d62',
    storageBucket: 'kaihe-54d62.appspot.com',
    iosClientId:
        '223539143896-4q9g4eil9k7dirvqds112r1lm95ch3n6.apps.googleusercontent.com',
    iosBundleId: 'com.kaihe.app',
  );
}
